list.txt:	list1.txt list2.txt list3.txt
	cp list1.txt list.txt ; cat list2.txt >> list.txt ; cat list3.txt >> list.txt ;

list1.txt:
	echo "list1" > list1.txt

list2.txt:
	echo "list2" > list2.txt

list3.txt:
	echo "list3" > list3.txt